In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import PolynomialFeatures
import seaborn as sns
import datetime 
import pytz
from pytz import timezone
import tarfile
from numpy import load
import os

In [2]:
d = np.load('/Users/marin/redhook/embeddings/sonycnode-b827eb208550.sonyc/2019-06-01/00/1559361628.56.npz')

In [3]:
d.files

['embedding', 'timestamps']

In [4]:
d['embedding']

array([[2.0931249, 1.1152985, 3.2679663, ..., 2.3449025, 1.4089253,
        2.4516468],
       [1.9170014, 1.479332 , 3.0609157, ..., 2.5557625, 1.5059618,
        2.823496 ],
       [2.0005364, 2.1422334, 2.4985769, ..., 2.5461915, 1.8356978,
        2.8371768],
       ...,
       [1.9174784, 1.605869 , 3.1989174, ..., 3.0292304, 1.6785302,
        2.3574908],
       [1.9913956, 1.5095303, 3.0157228, ..., 2.0276167, 1.5995463,
        2.4592245],
       [1.8192018, 1.6748338, 3.4832704, ..., 2.9015133, 1.5057862,
        2.7135656]], dtype=float32)

In [5]:
d['embedding']

array([[2.0931249, 1.1152985, 3.2679663, ..., 2.3449025, 1.4089253,
        2.4516468],
       [1.9170014, 1.479332 , 3.0609157, ..., 2.5557625, 1.5059618,
        2.823496 ],
       [2.0005364, 2.1422334, 2.4985769, ..., 2.5461915, 1.8356978,
        2.8371768],
       ...,
       [1.9174784, 1.605869 , 3.1989174, ..., 3.0292304, 1.6785302,
        2.3574908],
       [1.9913956, 1.5095303, 3.0157228, ..., 2.0276167, 1.5995463,
        2.4592245],
       [1.8192018, 1.6748338, 3.4832704, ..., 2.9015133, 1.5057862,
        2.7135656]], dtype=float32)

In [6]:
# df = pd.DataFrame(data=d['embedding'])
# df.head()

In [7]:
os.path.basename('/Users/marin/redhook/embeddings/sonycnode-b827eb208550.sonyc/2019-06-01/00/1559361628.56.npz')
os.path.basename('/Users/marin/redhook/embeddings/sonycnode-b827eb208550.sonyc/2019-06-01/00/1559361628.56.npz')[:10]

'1559361628'

Loops through all files in hour 0 of 6-01 and adds the timestamps to an array

In [8]:
timestamps_6_01_00 = np.empty(385)
data_6_01_00 = np.empty((385, 512))
count_6_01_00 = 0
day_01_00 = '/Users/marin/redhook/embeddings/sonycnode-b827eb208550.sonyc/2019-06-01/00'
for filename in sorted(os.listdir(day_01_00)):
    day_01_00_embedding = np.load(day_01_00 + '/' + filename)['embedding']
    for sec in range(11):
        timestamps_6_01_00[count_6_01_00] = str(int(os.path.basename(filename)[:10]) + sec)
        data_6_01_00[count_6_01_00] = day_01_00_embedding[sec]
        count_6_01_00 += 1
    #count_6_01_00 += 1
count_6_01_00

385

In [9]:
timestamps_6_01_00_dt = np.empty(385, dtype = datetime.datetime)
for i in range(385):
    j = timestamps_6_01_00[i]
    dt = datetime.datetime.utcfromtimestamp(j)
    dt = pytz.UTC.localize(dt)
    dt = dt.astimezone(pytz.timezone('US/Eastern'))
    timestamps_6_01_00_dt[i] = dt

In [10]:
df = pd.DataFrame(data_6_01_00)
df.insert(0, "Time", timestamps_6_01_00_dt, True)
df.head()

,Time,0,1,2,3,4,5,6,7,8,...,502,503,504,505,506,507,508,509,510,511
0,2019-06-01 00:00:28-04:00,2.093125,1.115299,3.267966,2.600699,4.386734,0.614799,1.508289,1.911545,1.631085,...,2.329870,2.693596,2.634851,2.617877,2.263398,2.064028,1.211207,2.344903,1.408925,2.451647
1,2019-06-01 00:00:29-04:00,1.917001,1.479332,3.060916,4.766980,3.649807,1.389943,1.774898,2.440066,1.192924,...,3.151508,2.616026,3.144591,1.897207,2.344439,2.753301,1.542656,2.555763,1.505962,2.823496
2,2019-06-01 00:00:30-04:00,2.000536,2.142233,2.498577,4.384803,3.449889,2.402933,1.792420,2.963485,1.735846,...,3.351357,2.549209,2.706580,2.142213,2.041494,2.246689,1.084968,2.546191,1.835698,2.837177
3,2019-06-01 00:00:31-04:00,1.856699,1.582061,2.593662,3.662261,3.377521,1.645816,1.405100,2.683466,1.198949,...,2.656243,2.167135,3.039538,1.907364,1.839635,2.889525,0.995547,2.107294,2.030357,3.319138
4,2019-06-01 00:00:32-04:00,1.896574,1.591261,2.830297,4.182943,3.380369,1.186396,1.081441,2.225049,1.322107,...,3.404805,2.849727,2.882296,2.141266,1.937293,2.918287,1.119735,2.479955,1.673045,2.788664

Same as above, but for the whole day

In [25]:
timestamps_6_01 = np.empty(9537)
data_6_01 = np.empty((9537, 512))
count_6_01 = 0
day_01 = '/Users/marin/redhook/embeddings/sonycnode-b827eb208550.sonyc/2019-06-01'
for dirname in sorted(os.listdir(day_01)):
    for filename_1 in sorted(os.listdir(day_01 + '/' + dirname)):
#         print(filename_1 + " " + dirname_1)
        day_01_embedding = np.load(day_01 + '/' + dirname + '/' + filename_1)['embedding']
        for sec_1 in range(11):
            timestamps_6_01[count_6_01] = str(int(os.path.basename(filename_1)[:10]) + sec_1)
            data_6_01[count_6_01] = day_01_embedding[sec_1]
            count_6_01 += 1

In [26]:
timestamps_6_01_dt = np.empty(9537, dtype = datetime.datetime)
for i in range(9537):
    j = timestamps_6_01[i]
    dt = datetime.datetime.utcfromtimestamp(j)
    dt = pytz.UTC.localize(dt)
    dt = dt.astimezone(pytz.timezone('US/Eastern'))
    timestamps_6_01_dt[i] = dt

In [29]:
day_01_df = pd.DataFrame(data_6_01)
day_01_df.insert(0, "Time", timestamps_6_01_dt, True)
day_01_df.tail()

,Time,0,1,2,3,4,5,6,7,8,...,502,503,504,505,506,507,508,509,510,511
9532,2019-06-01 23:58:04-04:00,1.256165,1.629046,2.780099,3.507525,3.552612,1.586547,1.327846,1.559000,1.311527,...,2.482014,2.412203,3.680104,1.573512,2.017706,2.750537,1.031552,2.343161,1.674596,2.657019
9533,2019-06-01 23:58:05-04:00,1.417175,1.574511,2.730569,3.654880,3.966511,1.488733,1.438324,1.466175,1.571570,...,2.324653,2.153596,3.366831,1.473867,2.310448,1.681509,1.161637,2.041306,1.735808,2.352880
9534,2019-06-01 23:58:06-04:00,1.552803,1.666663,2.471927,3.355394,3.596159,1.405086,1.119313,2.417684,1.275138,...,2.867661,2.022134,3.044971,1.708414,2.361706,1.428441,1.265338,2.088488,1.468976,1.975224
9535,2019-06-01 23:58:07-04:00,1.641850,1.511594,2.891329,3.710870,3.666551,1.675946,1.685685,1.670958,1.503443,...,2.805249,2.329516,3.452280,1.393967,2.183595,1.786110,1.081113,2.265397,1.614978,3.059705
9536,2019-06-01 23:58:08-04:00,1.791041,1.531177,3.659442,4.340420,3.490789,1.915224,1.365899,1.161948,1.287995,...,2.205489,2.218124,3.668745,2.568184,2.063264,2.244980,2.381623,3.098542,1.628558,2.714632